namespace UnitTests.Constants
{
    public static class TokenConstants
    {
        public const string TestToken = "GTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTWGTQWQYTW";
    }
}
